### ISSUE TITLE
定義開發框架

### ISSUE THREAD

**Issue by arealclimber** [CAFECA-IO/TideBit-DeFi#1]
- [x] Initial Blank Project
- [x] wiki: how to develop
- [x] KM: Tailwind
https://github.com/CAFECA-IO/KnowledgeManagement/issues/7

**Comment by Luphia** [comment]
- Initial Blank Project

**Comment by arealclimber** [comment]
taking 2 hrs

https://github.com/CAFECA-IO/TideBit-DeFi/wiki/How-to-develop
