### ISSUE TITLE
偵測用戶 input 全形數字

### ISSUE THREAD

**Issue by arealclimber** [CAFECA-IO/TideBit-DeFi#1000]
在下單區加入偵測全形數字然後能轉換成數字的功能，讓用戶不用切換輸入法就能下單

ref:

- [輸入框中轉英](https://medium.com/@box5151/%E8%BC%B8%E5%85%A5%E6%A1%86%E4%B8%AD%E8%BD%89%E8%8B%B1-c58e213bb1a6)
- [JS如何判斷文字是全形還是半形](https://topic.alibabacloud.com/tc/a/js-how-to-determine-whether-the-text-is-full-width-or-half-width-reproduced_1_11_30554149.html)
- [JS全形字轉換為半形](https://www.webdo.com.tw/blogCnt.php?cnt_id=16)
- [從 React 原始碼看 keyPress 與 keyDown 事件](https://blog.techbridge.cc/2019/03/23/react-keyboard-event/)

**Comment by Julian0701** [comment]
- [keyCode 已被棄用](https://developer.mozilla.org/en-US/docs/Web/API/KeyboardEvent/keyCode)

**Comment by Julian0701** [comment]
- take 7 hrs
- 目前沒有找到解法

**Comment by Julian0701** [comment]
### 踩坑記錄

#### 方法一：透過 ****keyCode 切換輸入的字元****

參考來源：

- [[輸入框中轉英](https://medium.com/@box5151/%E8%BC%B8%E5%85%A5%E6%A1%86%E4%B8%AD%E8%BD%89%E8%8B%B1-c58e213bb1a6)](https://medium.com/@box5151/%E8%BC%B8%E5%85%A5%E6%A1%86%E4%B8%AD%E8%BD%89%E8%8B%B1-c58e213bb1a6)
- [[從 React 原始碼看 keyPress 與 keyDown 事件](https://blog.techbridge.cc/2019/03/23/react-keyboard-event/)](https://blog.techbridge.cc/2019/03/23/react-keyboard-event/)

失敗原因：[[keyCode 已被棄用](https://developer.mozilla.org/en-US/docs/Web/API/KeyboardEvent/keyCode)](https://developer.mozilla.org/en-US/docs/Web/API/KeyboardEvent/keyCode)

#### 方法二：使用 ime-mode 攔截中文輸入

失敗原因：i[[me-mode 不支援 Chrome](https://blog.csdn.net/poppyCL/article/details/102931375)](https://blog.csdn.net/poppyCL/article/details/102931375)

---

### 替代方案
在 Trading Input 附近加上提醒用戶切換輸入法的文字

**Comment by arealclimber** [comment]
無法實作原本計畫的功能，但由 @Julian0701 實作替代方案，PR https://github.com/CAFECA-IO/TideBit-DeFi/pull/1449/files#diff-a5c6a62a92b9736f51d8d9390b2ef589fc80674e0b01d63514708eb8282ca50f
