### ISSUE TITLE
在 My asset 點 Open position 要關倉，UpdateFormModal 的 PNL 顯示可能是--

### ISSUE THREAD

**Issue by arealclimber** [CAFECA-IO/TideBit-DeFi#1029]
![截圖 2023-07-25 下午6 22 24](https://github.com/CAFECA-IO/TideBit-DeFi/assets/114177573/890f9b42-a8d8-4d27-a83f-c1b44f83e667)

**Comment by Julian0701** [comment]
<img width="986" alt="image" src="https://github.com/CAFECA-IO/TideBit-DeFi/assets/114177573/653adc63-31c1-4b22-9335-de75dfef516e">

原本傳入的是 cfdData.targetAsset ，導致 predictCFDClosePrice 回傳 0 ，PNL 也算錯
改成 cfdData.ticker 就解決了

- take 1.5 hr
