### ISSUE TITLE
[BUG] CFD Share 資料錯誤

### ISSUE THREAD

**Issue by arealclimber** [CAFECA-IO/TideBit-DeFi#1030]
顯示instId
![image](https://github.com/CAFECA-IO/TideBit-DeFi/assets/20677913/4b721402-e106-4de8-8cf2-6d230281239f)

**Comment by TzuHanLiang** [comment]
- [參考](https://github.com/CAFECA-IO/tbd-backend/issues/161)

**Comment by arealclimber** [comment]
taking 1 hrs
