### ISSUE TITLE
[BUG] 手機版 Trade Tab Input 調整

### ISSUE THREAD

**Issue by Julian0701** [CAFECA-IO/TideBit-DeFi#1033]
- [x] 輸入延遲
- [x] 修正無法輸入小數點的問題

**Comment by Julian0701** [comment]
[MAC Debug](https://mrcodingroom.freesite.host/tipiphone-safari-%E5%9C%A8windows-mac%E4%B8%8Adebug/)

**Comment by arealclimber** [comment]
taking 4 hrs

**Comment by arealclimber** [comment]
#1257
