### ISSUE TITLE
CandlestickChart 效能優化

### ISSUE THREAD

**Issue by Julian0701** [CAFECA-IO/TideBit-DeFi#1041]
目前蠟燭圖的做法是一拿到新資料就重畫整張圖，造成 /trade 頁面的許多功能(例如手機版的點擊事件)被拖慢，因此需要找出改良的方法

根據 [KM](https://github.com/CAFECA-IO/KnowledgeManagement/blob/master/NextJs/state_management_for_react.md) 得知是 context 的 CandlestickChart Data更新，造成其他 component 也每0.1秒重跑一次造成的效能問題，~效能優化打算用 Zustand 重構 context 來解決~

> [#1457 重構之後，在行動版上，重畫整張蠟燭圖還是非常耗費效能，會導致按鈕不好按，最好的解決方案是使用d3.js自己客製化圖表，但需要的執行時間較長，workaround 是把行動版的蠟燭圖改成每 1 秒更新一次，按鈕會好按很多](https://github.com/CAFECA-IO/TideBit-DeFi/issues/1041#issuecomment-1835671908)

**Comment by arealclimber** [comment]
taking 5 hrs
remaining 4 hrs

**Comment by arealclimber** [comment]
taking 2 hrs
remaining 2 hrs
