### ISSUE TITLE
前後端討論 PNL value 正負號

### ISSUE THREAD

**Issue by arealclimber** [CAFECA-IO/TideBit-DeFi#1076]
由 #1067 衍生

PNL 有 type 跟 value ，討論結果是用 type 來判斷正負號，value 去掉正負號

**Comment by TzuHanLiang** [comment]
<img width="1111" alt="Screenshot 2023-08-10 at 11 57 23 AM" src="https://github.com/CAFECA-IO/TideBit-DeFi/assets/17249354/d8d4ed9f-d446-4e45-b243-bf47710330d1">

後端調整後，排名會出現異常，會需要額外開票調整

**Comment by arealclimber** [comment]
經過討論，將 PNL value 改回顯示正負號，去掉 PNL type ，直接用 value 來判斷損益
前端部分由 #1101 處理
