### ISSUE TITLE
[BUG] Leaderboard 排名顯示優化

### ISSUE THREAD

**Issue by JodieWu** [CAFECA-IO/TideBit-DeFi#1077]
- 我的排名沒有黏在該黏的地方，出現兩個相同的名次，看起來怪怪的
<img width="1605" alt="截圖 2023-08-02 下午12 39 15" src="https://github.com/CAFECA-IO/TideBit-DeFi/assets/98379087/d538cbfb-ee3d-4e1a-b8ba-792416945f3c">

**Comment by Julian0701** [comment]
- take 3 hrs
