### ISSUE TITLE
[BUG] Personal Achievement 未顯示排名

### ISSUE THREAD

**Issue by JodieWu** [CAFECA-IO/TideBit-DeFi#1078]
- Personal Achievement 皇冠旁邊應該要顯示名次，這裡沒有
<img width="458" alt="截圖 2023-08-02 下午12 40 01" src="https://github.com/CAFECA-IO/TideBit-DeFi/assets/98379087/4f98730e-d3db-4db0-8d6b-06ee13ba93a8">

**Comment by Julian0701** [comment]
於 #1093 處理
