### ISSUE TITLE
[BUG] Deposit 幣種顯示問題

### ISSUE THREAD

**Issue by JodieWu** [CAFECA-IO/TideBit-DeFi#1079]
-  Deposit 這邊 Tether 不應該有“'s”
<img width="300" alt="截圖 2023-08-02 下午12 40 56" src="https://github.com/CAFECA-IO/TideBit-DeFi/assets/98379087/0e663027-56e8-4d2a-ad1e-abfccc90f172">

**Comment by arealclimber** [comment]
taking 0.5 hr
API: https://api.tidebit-defi.com/currencies
![image](https://github.com/CAFECA-IO/TideBit-DeFi/assets/20677913/e9ecfeed-886b-47f6-8a0a-d7641c4d268a)

**Comment by TzuHanLiang** [comment]
- take 1hrs
