### ISSUE TITLE
[BUG] My Asset 紀錄顯示方式修正

### ISSUE THREAD

**Issue by JodieWu** [CAFECA-IO/TideBit-DeFi#1080]
- 設計稿中，My Asset 顯示約十筆資料後，底部應該要有 See more Button, 按了才會繼續往下展開，依次類推，但目前沒有，隨著資料越多會深不見底，滑不到Footer
<img width="1511" alt="截圖 2023-08-02 下午12 44 40" src="https://github.com/CAFECA-IO/TideBit-DeFi/assets/98379087/6330bb40-d9cd-454c-8ee5-d60fa1306d29">

**Comment by Julian0701** [comment]
- take 4 hrs
