### ISSUE TITLE
[BUG] Landing page RWD

### ISSUE THREAD

**Issue by arealclimber** [CAFECA-IO/TideBit-DeFi#1153]
[Ref](https://github.com/CAFECA-IO/TideBit-DeFi/issues/1141#issuecomment-1691308559)

依照設計稿置中垂直擺放
<img width="373" alt="截圖 2023-08-24 下午5 07 45" src="https://github.com/CAFECA-IO/TideBit-DeFi/assets/98379087/210ef9ca-c85a-4ccc-831f-d2d1a81b0a15">

下載報告按鈕置中
<img width="376" alt="截圖 2023-08-24 下午5 08 12" src="https://github.com/CAFECA-IO/TideBit-DeFi/assets/98379087/26e56dcf-8ab3-428c-9a19-33c461123d93">

整個頁面左右 padding 至少 16 px
<img width="375" alt="截圖 2023-08-24 下午5 08 46" src="https://github.com/CAFECA-IO/TideBit-DeFi/assets/98379087/380feb66-9671-4099-9833-e5880a8d07f4">

**Comment by RexBearIU** [comment]
Still not fixed and there are more bugs -> [20230905 testresult](https://github.com/CAFECA-IO/Documents/blob/main/TBD/testresult/TBDTC000002/20230905.md)

**Comment by arealclimber** [comment]
taking 1 hr
- 加上整理首頁其他字型跟 padding
