### ISSUE TITLE
[BUG] Landing page href problem

### ISSUE THREAD

**Issue by RexBearIU** [CAFECA-IO/TideBit-DeFi#1180]
- Environment Description
  - Machine：Mac Book Pro 15-inch, 2018, 2.6 GHz 6-Core Intel Core i7
  - OS version：macOS Ventura Version 13.5
  - Browser version：Google Chrome Version 116.0.5845.187
- How to reproduce
Just open the landing page
- Current Result

1. 這邊Blockchain的連結目前連接回tidebit defi首頁
![截圖 2023-09-06 下午5 10 19](https://github.com/CAFECA-IO/TideBit-DeFi/assets/123862185/e4375b38-e5e8-4d3c-afc8-9af5be572cfa)

2. 這邊底下 BAIFA 的連結無論當前語言都會連到英文版
![截圖 2023-09-06 下午5 11 20](https://github.com/CAFECA-IO/TideBit-DeFi/assets/123862185/0afd0ab0-a46e-42bf-877b-658f5e2d1daa)

這邊下載 APP 的按鈕目前無作用
![截圖 2023-09-06 下午5 12 08](https://github.com/CAFECA-IO/TideBit-DeFi/assets/123862185/a548b4ef-e371-4813-a88a-696ff5fb7ccc)

- Expect Result
1. 應該是要連到BAIFA去，還未開發完就連到 Coming soon
2. 應該要隨語系切換連到相對應的官網語系
3. 雖還未開發完ＡＰＰ，但應該要連到 Coming soon

**Comment by arealclimber** [comment]
taking 1.5 hrs

**Comment by RexBearIU** [comment]
APP 下載的按鈕目前還是無作用

**Comment by RexBearIU** [comment]
09/23 12:00 新的Merge已修復

**Comment by RexBearIU** [comment]
10/03 第一點的網址還未更正

**Comment by arealclimber** [comment]
taking 10 min
