### ISSUE TITLE
[BUG] landing page baifa report download problem

### ISSUE THREAD

**Issue by RexBearIU** [CAFECA-IO/TideBit-DeFi#1186]
語言為繁體中文與簡體中文時點選任意人工智慧監管報告下載出現檔案下載錯誤
- Environment Description
  - Machine: MacBook Pro (13-inch, 2017, Two Thunderbolt 3 ports)
  - OS version: macOS Catalina 10.15.7（19H2026）
  - Browser version: Microsoft Edge v116.0.1938.76
- How to reproduce
Just open the landing page
- Current Result
<img width="1440" alt="截圖 2023-09-07 下午5 15 17" src="https://github.com/CAFECA-IO/TideBit-DeFi/assets/123862185/51574fcd-27bb-4744-aaeb-13c8c4f4aad8">

- Expect Result
Download the English report since we don't have others.

**Comment by arealclimber** [comment]
用 `<Link>` 時，隨著多語系切換，url 會加上該語系的前綴，例如切到繁體中文，會加上 /tw；PDF 下載適合用 `<a>`
taking 1 hr
