### ISSUE TITLE
[BUG] Close position receipt UI bug 

### ISSUE THREAD

**Issue by RexBearIU** [CAFECA-IO/TideBit-DeFi#1188]
Close position receipt TP/SL should be -/- like an open receipt 

- Environment Description
  - Machine: iMac Pro 2017
  - OS version: MacOS Ventura 13.5.2 (22G91)
  - Browser version: Google Chrome 116.0.5845.179 (x86_64)
- How to reproduce
connect any account and go to CFD trade
- Current Result

<img width="300" alt="截圖 2023-09-08 下午5 00 46" src="https://github.com/CAFECA-IO/TideBit-DeFi/assets/123862185/4ec69ab0-f2b7-4fe8-9203-e66a3be5e9ec">

- Expect Result
<img width="300" alt="截圖 2023-09-08 下午5 00 46" src="https://github.com/CAFECA-IO/TideBit-DeFi/assets/123862185/1bd1346a-f695-48a2-a5f7-adb44f512a6f">

**Comment by arealclimber** [comment]
taking 0.5 hrs
