### ISSUE TITLE
[BUG]CFD trade layout error

### ISSUE THREAD

**Issue by RexBearIU** [CAFECA-IO/TideBit-DeFi#1198]
- Environment Description
  - Machine: Desktop
  - OS version: Windows 10
  - Browser version: Brave v1.56.14 Chromium v115.0.5790.114
- How to reproduce
connect any account and go to CFD trade
- Current Result

CFD trade layout error after opening Close at profit and Close at loss .

![image (1)](https://github.com/CAFECA-IO/TideBit-DeFi/assets/123862185/78a36a82-9ec7-4642-8764-b9a6d161349d)

- Expect Result

It shouldn't overlap.

**Comment by RexBearIU** [comment]
More BUG improvement 

[reference](https://github.com/CAFECA-IO/TideBit-DeFi/issues/1207)

**Comment by arealclimber** [comment]
taking 0.5 hr
- 正常顯示 tp/sl ，但還沒將整個交易tab改成手風琴效果

remaining 1.5 hrs

**Comment by arealclimber** [comment]
taking 1.5 hrs
