### ISSUE TITLE
[BUG] My asset layout error

### ISSUE THREAD

**Issue by RexBearIU** [CAFECA-IO/TideBit-DeFi#1202]
- Environment Description
  - Machine: MacBook Pro (13-inch, 2017, Two Thunderbolt 3 ports)
  - OS version: macOS Catalina 10.15.7（19H2026）
  - Browser version: Microsoft Edge v116.0.1938.76
- How to reproduce
 Open the my asset page
- Current Result

<img width="1248" alt="截圖 2023-09-12 下午2 20 27" src="https://github.com/CAFECA-IO/TideBit-DeFi/assets/123862185/004150ee-4ef2-4320-8cbb-980f87a25284">

- Expect Result
Trading Type, calendar and Search should be on the same line.

**Comment by Julian0701** [comment]
- take 1 hr
- 改用 grid 排版
