### ISSUE TITLE
[BUG] My asset trade log's default time interval error

### ISSUE THREAD

**Issue by RexBearIU** [CAFECA-IO/TideBit-DeFi#1203]
- Environment Description
  - Machine: MacBook Pro (13-inch, 2017, Two Thunderbolt 3 ports)
  - OS version: macOS Catalina 10.15.7（19H2026）
  - Browser version: Microsoft Edge v116.0.1938.76
- How to reproduce
 Open the my asset page
- Current Result

The default time interval for the trade log does not match the timestamp of the filtered log.
<img width="820" alt="截圖 2023-09-12 下午2 20 11" src="https://github.com/CAFECA-IO/TideBit-DeFi/assets/123862185/22a63117-be1f-4f09-af91-475b95961567">

- Expect Result
The default time interval for the trade log should match the timestamp of the filtered log.

**Comment by Julian0701** [comment]
- take 1 hr
- 新增 useEffect ，讓元件載入後先取得今日區間中的資料
