### ISSUE TITLE
[BUG] CFD sharing number photo error

### ISSUE THREAD

**Issue by RexBearIU** [CAFECA-IO/TideBit-DeFi#1204]
- Environment Description
  - Machine: MacBook Pro (13-inch, 2017, Two Thunderbolt 3 ports)
  - OS version: macOS Catalina 10.15.7（19H2026）
  - Browser version: Microsoft Edge v116.0.1938.76
- How to reproduce
From my asset share a close position log
- Current Result
![Screenshot_2023-09-12-14-19-13-710_com facebook katana](https://github.com/CAFECA-IO/TideBit-DeFi/assets/123862185/18867b82-9ac7-4d7d-a859-56d6c3f538b4)

- Expect Result
The number should match the close position log.

**Comment by arealclimber** [comment]
taking 2 hrs
