### ISSUE TITLE
[BUG] Leaderboard Weekly and Monthly UI error

### ISSUE THREAD

**Issue by RexBearIU** [CAFECA-IO/TideBit-DeFi#1205]
- Environment Description
  - Machine: MacBook Pro (13-inch, 2017, Two Thunderbolt 3 ports)
  - OS version: macOS Catalina 10.15.7（19H2026）
  - Browser version: Microsoft Edge v116.0.1938.76
- How to reproduce
 Open the leaderboard with an unrecorded account
- Current Result
![截圖 2023-09-12 下午4 05 32](https://github.com/CAFECA-IO/TideBit-DeFi/assets/123862185/f883e175-2dbd-497d-95a9-ce3568a60424)
<img width="1136" alt="截圖 2023-09-12 下午4 07 27" src="https://github.com/CAFECA-IO/TideBit-DeFi/assets/123862185/1699bfce-4b96-424d-9a7f-d8e9986d7fba">

- Expect Result
It is not necessary to display the rank twice.

**Comment by Julian0701** [comment]
- take 1.5 hr
