### ISSUE TITLE
Tidebit Defi all pages lack of element id or class

### ISSUE THREAD

**Issue by RexBearIU** [CAFECA-IO/TideBit-DeFi#1208]
lack of element ID or class may lead to hard maintenance

**Comment by RexBearIU** [comment]
[TideBit-DeFi 無障礙功能改良](https://pagespeed.web.dev/analysis/https-tidebit-defi-com/jp45al04ot?utm_source=search_console&form_factor=desktop&hl=zh_TW)

**Comment by Julian0701** [comment]
- take 8 hrs
- remain 3 hrs

**Comment by Julian0701** [comment]
- take 7 hrs
