### ISSUE TITLE
isNumber function 需要改善

### ISSUE THREAD

**Issue by arealclimber** [CAFECA-IO/TideBit-DeFi#1213]
將 undefined 或 undefined.data 資料傳入 isNumber 會造成 crash，在外層包 try-catch 也無法成功接到錯誤

**Comment by TzuHanLiang** [comment]
> 將 undefined 或 undefined.data 資料傳入 isNumber 會造成 crash，在外層包 try-catch 也無法成功接到錯誤

- 不應該傳入 undefined.data 而是改用 undefined?.data

**Comment by TzuHanLiang** [comment]
請 @arealclimber  幫忙測試

**Comment by arealclimber** [comment]
taking 1 hrs
https://github.com/CAFECA-IO/TideBit-DeFi/pull/1256#pullrequestreview-1643283493
