### ISSUE TITLE
[BUG] CFD close position layout error

### ISSUE THREAD

**Issue by RexBearIU** [CAFECA-IO/TideBit-DeFi#1216]
- Environment Description
  - Machine: Desktop
  - OS version: Windows 10
  - Browser version: Brave v1.56.14 Chromium v115.0.5790.114
- How to reproduce
Set up guaranteed Stop in any position and reload the trade page.
- Current Result

CFD close position receipt guaranteed stop fee $NAN  .

![image (2)](https://github.com/CAFECA-IO/TideBit-DeFi/assets/123862185/8fe371cd-9338-4aa4-aa6d-748cd1839293)

- Expect Result

It should have number.

**Comment by arealclimber** [comment]
guaranteed stop fee i18n bug

![image](https://github.com/CAFECA-IO/TideBit-DeFi/assets/20677913/8033676b-eda0-4f46-b0a7-248af8a5d8ac)

**Comment by arealclimber** [comment]
History modal NaN bug

![image](https://github.com/CAFECA-IO/TideBit-DeFi/assets/20677913/6419f96b-ae5a-47a4-a28a-f67ee533a19f)

**Comment by arealclimber** [comment]
taking 0.5 hrs
