### ISSUE TITLE
[BUG] CFD trade receipt layout error

### ISSUE THREAD

**Issue by RexBearIU** [CAFECA-IO/TideBit-DeFi#1219]
- Environment Description
  - Machine: Desktop
  - OS version: Windows 10
  - Browser version: Brave v1.56.14 Chromium v115.0.5790.114
  - emulate Iphone XR
- How to reproduce
In CFD Trade close position 
- Current Result

CFD close position button error

![image (2)](https://github.com/CAFECA-IO/TideBit-DeFi/assets/123862185/8fe371cd-9338-4aa4-aa6d-748cd1839293)
<img width="371" alt="Screenshot 2023-09-15 at 4 33 10 PM" src="https://github.com/CAFECA-IO/TideBit-DeFi/assets/98379087/a5079ca6-27d0-470d-b22c-7b7bc8a432e5">

- Expect Result

It shouldn't overlap.

**Comment by arealclimber** [comment]
更新 UI #1286

**Comment by arealclimber** [comment]
由 #1286 修正錯誤

**Comment by arealclimber** [comment]
由 #1286 修正錯誤，此 issue 沒有花時間執行
