### ISSUE TITLE
[BUG] CFD Trade href language problem

### ISSUE THREAD

**Issue by RexBearIU** [CAFECA-IO/TideBit-DeFi#1231]
- Environment Description
  - Machine: iMac Pro 2017
  - OS version: MacOS Ventura 13.5.2 (22G91)
  - Browser version: Google Chrome 116.0.5845.179 (x86_64)
- How to reproduce
 Go to CFD trade and click href
- Current Result
![截圖 2023-09-19 上午9 19 43](https://github.com/CAFECA-IO/TideBit-DeFi/assets/123862185/66442f99-899d-4dea-ae44-bd4643542a22)
![截圖 2023-09-19 上午9 20 21](https://github.com/CAFECA-IO/TideBit-DeFi/assets/123862185/cca03e76-328c-47a2-b944-dfae153a29c6)
![截圖 2023-09-19 上午9 20 34](https://github.com/CAFECA-IO/TideBit-DeFi/assets/123862185/86eeb28d-dcaf-4340-83ce-ef8ae558032c)

- Expect Result
![截圖 2023-09-19 上午9 21 06](https://github.com/CAFECA-IO/TideBit-DeFi/assets/123862185/e0de4a67-6662-442b-82a4-43457612ab9d)
![截圖 2023-09-19 上午9 21 27](https://github.com/CAFECA-IO/TideBit-DeFi/assets/123862185/68b239ec-3357-4d05-a545-32b3d4d50fe2)

**Comment by Julian0701** [comment]
- take 1 hr
- 暫時使用 `if else` 和 `replace` 作為替代方案
