### ISSUE TITLE
[BUG] Landing page console error message

### ISSUE THREAD

**Issue by RexBearIU** [CAFECA-IO/TideBit-DeFi#1233]
- Environment Description
    - Machine: MacBook Air M1, 2020
    - OS version: macOS Ventura 13.5.2
    - Browser version: Brave v1.58.124 Chromium v117.0.5938.62
- How to reproduce
open tidebit defi landing page.
- Current Result
There are invalid data interface in getWebsiteReserve func.
![image (3)](https://github.com/CAFECA-IO/tbd-backend/assets/123862185/076a1876-0e25-48ad-abd9-097c8b3bef45)

- Expect Result

It should not have .

**Comment by arealclimber** [comment]
taking 1 hr

上述錯誤訊息來自我的電腦的 brave extension 的錯誤，改成其他瀏覽器就不會出現該錯誤訊息





![Screenshot 2023-09-19 at 18 46 17](https://github.com/CAFECA-IO/TideBit-DeFi/assets/20677913/1a46920e-9a85-47dd-b53c-9b12be14cd65)
![Screenshot 2023-09-19 at 18 46 01](https://github.com/CAFECA-IO/TideBit-DeFi/assets/20677913/41051be2-d9ee-49b8-989e-86effcd270a6)
