### ISSUE TITLE
關倉/暫停交易/Demo mode通知訊息小視窗

### ISSUE THREAD

**Issue by arealclimber** [CAFECA-IO/TideBit-DeFi#124]
[關倉](https://xd.adobe.com/view/b4bc1f81-78f4-4de9-979f-20cb0d457d70-e1ef/screen/28794960-879c-4c35-890f-90acc70772a3/)｜[暫停交易](https://xd.adobe.com/view/b4bc1f81-78f4-4de9-979f-20cb0d457d70-e1ef/screen/687a33e6-5b88-481e-b2f9-4d052b00dd1d/)｜[Demo mode ](https://xd.adobe.com/view/b4bc1f81-78f4-4de9-979f-20cb0d457d70-e1ef/screen/3c0488ca-5d94-4503-bc04-318400b2cbba/)

**Comment by Julian0701** [comment]
- take 6.5 hrs
