### ISSUE TITLE
將 BAIFA 報表接到 TideBit-DeFi 首頁

### ISSUE THREAD

**Issue by Julian0701** [CAFECA-IO/TideBit-DeFi#1246]
![image](https://github.com/CAFECA-IO/TideBit-DeFi/assets/114177573/74407225-e8a9-4456-9b2d-f10c59d654d6)
暫時先直接貼上連結

**Comment by arealclimber** [comment]
taking 2 hrs
- 修改 timestampToString function
- 將報表下載連結改成連到 BAIFA
- BAIFA 連結加上 project id
