### ISSUE TITLE
[BUG] Landing page download error

### ISSUE THREAD

**Issue by RexBearIU** [CAFECA-IO/TideBit-DeFi#1249]
語言為繁體中文與簡體中文時點選下載報告出現檔案下載錯誤
- Environment Description
  - Machine: MacBook Pro (13-inch, 2017, Two Thunderbolt 3 ports)
  - OS version: macOS Catalina 10.15.7（19H2026）
  - Browser version: Microsoft Edge v116.0.1938.76
- How to reproduce
Just open the landing page
- Current Result
![截圖 2023-09-23 上午10 43 43](https://github.com/CAFECA-IO/TideBit-DeFi/assets/123862185/505b2003-99dc-4951-b805-c2486f1ec475)

- Expect Result
Download the right report .

**Comment by arealclimber** [comment]
- [ ] reserve report 連到 BAIFA balance sheet

**Comment by arealclimber** [comment]
taking 0.5 hr
