### ISSUE TITLE
開倉後 Open sub tab 的 skeleton

### ISSUE THREAD

**Issue by arealclimber** [CAFECA-IO/TideBit-DeFi#126]
-  [Suspense - React beta doc](https://beta.reactjs.org/reference/react/Suspense)

![image](https://user-images.githubusercontent.com/20677913/211238985-7e0c331e-69f8-4ea9-895b-59cd401cce00.png)

Ref: 
- 設計稿
  - [TideBit DeFi 設計稿電腦版 Spec](https://xd.adobe.com/view/920d36bd-2d1a-4edd-8a2a-824445f1d3b0-c75e/screen/1efeff4c-2c35-4644-aa82-40fd9e9bf9fe/specs/)
  - [TideBit DeFi 設計稿手機版 Spec](https://xd.adobe.com/view/b4bc1f81-78f4-4de9-979f-20cb0d457d70-e1ef/screen/52e1328b-a83e-4c59-a3be-f5ca82af482f)
  - [skeleton1](https://xd.adobe.com/view/2ba73e9b-23f4-4521-8822-49a8e2a595a0-7ef4/grid)
  - [skeleton2](https://xd.adobe.com/view/acc31879-2cf7-4625-88e8-98a7bcbe5db3-f990/grid)
- Sequence Diagram
  - [Sequence Diagram 001 (interaction between user, frontend and backend)](https://github.com/CAFECA-IO/Documents/blob/main/TBD/TBDSD00001.md)
  - [Sequence Diagram 002 (background mechanism)](https://github.com/CAFECA-IO/Documents/blob/main/TBD/TBDSD00002.md)
- Diagrams
  - [Component Diagram](https://github.com/CAFECA-IO/Documents/blob/main/TBD/TBDCP00001.md)
  - [Class Diagram](https://github.com/CAFECA-IO/Documents/blob/main/TBD/TBDCD00001.md)
  - [Use Cases Diagram](https://github.com/CAFECA-IO/Documents/blob/main/TBD/TBDUC00001.md)

**Comment by Julian0701** [comment]
- take 4 hrs
由於 Loading animation 還沒做好，這張票延後處理

**Comment by Julian0701** [comment]
研究 react skeleton

- take 4 hrs

**Comment by Julian0701** [comment]
- take 2 hrs

done
