### ISSUE TITLE
[BUG] My assets default time interval error

### ISSUE THREAD

**Issue by RexBearIU** [CAFECA-IO/TideBit-DeFi#1267]
- Environment Description
  - Machine: MacBook Pro (13-inch, 2017, Two Thunderbolt 3 ports)
  - OS version: macOS Catalina 10.15.7（19H2026）
  - Browser version: Microsoft Edge v116.0.1938.76
- How to reproduce
Just open the landing page
- Current Result

Current interval is today.
[ref](https://github.com/CAFECA-IO/TideBit-DeFi/issues/1254)

- Expect Result
Should be 30 days.

**Comment by Julian0701** [comment]
- take 2 hrs
- 修正 date picker 和 receipt filter 錯誤
