### ISSUE TITLE
[BUG] Update position input error

### ISSUE THREAD

**Issue by RexBearIU** [CAFECA-IO/TideBit-DeFi#1270]
- Environment Description
  - Machine: MacBook Pro (13-inch, 2017, Two Thunderbolt 3 ports)
  - OS version: macOS Catalina 10.15.7（19H2026）
  - Browser version: Microsoft Edge v116.0.1938.76
- How to reproduce
Just open the landing page
- Current Result

https://github.com/CAFECA-IO/TideBit-DeFi/assets/123862185/79b5b9b2-740e-4043-b3c9-f2775c960e31

- Expect Result
Should be corrected change.

**Comment by arealclimber** [comment]
taking 1 hr
