### ISSUE TITLE
[BUG] Update position receipt error

### ISSUE THREAD

**Issue by RexBearIU** [CAFECA-IO/TideBit-DeFi#1271]
- Environment Description
  - Machine: MacBook Pro (13-inch, 2017, Two Thunderbolt 3 ports)
  - OS version: macOS Catalina 10.15.7（19H2026）
  - Browser version: Microsoft Edge v116.0.1938.76
- How to reproduce
Just open the landing page
- Current Result

Guaranteed fee is $NAN.
![image (3)](https://github.com/CAFECA-IO/TideBit-DeFi/assets/123862185/5b9467f6-1f2f-4abe-a4c2-a411e917de11)

- Expect Result
It should show guaranteed fee.

**Comment by arealclimber** [comment]
taking 1 hr
