### ISSUE TITLE
[BUG] My asset trade log lag

### ISSUE THREAD

**Issue by RexBearIU** [CAFECA-IO/TideBit-DeFi#1273]
- Environment Description
  - Machine: MacBook Pro (13-inch, 2017, Two Thunderbolt 3 ports)
  - OS version: macOS Catalina 10.15.7（19H2026）
  - Browser version: Microsoft Edge v116.0.1938.76
- How to reproduce
Just open the landing page
- Current Result

<img width="318" alt="截圖 2023-09-08 下午5 00 46" src="https://github.com/CAFECA-IO/TideBit-DeFi/assets/123862185/39cfe41b-2aaa-41ba-a5e4-9f9a96086015">
<img width="1440" alt="截圖 2023-09-08 下午5 01 42" src="https://github.com/CAFECA-IO/TideBit-DeFi/assets/123862185/5a4d488d-7e64-46ae-bee5-9157ec9c9fbb">

- Expect Result
Should be the same.

**Comment by Julian0701** [comment]
- take 1 hr
