### ISSUE TITLE
[BUG] CFD trade my favorite error

### ISSUE THREAD

**Issue by RexBearIU** [CAFECA-IO/TideBit-DeFi#1289]
- Environment Description
  - Machine: MacBook Pro (13-inch, 2017, Two Thunderbolt 3 ports)
  - OS version: macOS Ventura 13.5.2（22G91）
  - Browser version: Microsoft Edge v116.0.1938.76
- How to reproduce
cancel the favorite star and reopen browser
- Current Result
<img width="681" alt="截圖 2023-10-02 下午5 36 01" src="https://github.com/CAFECA-IO/TideBit-DeFi/assets/123862185/33c8f445-6b57-4dc2-aeb8-60446bb2eed3">
<img width="574" alt="截圖 2023-10-02 下午5 40 01" src="https://github.com/CAFECA-IO/TideBit-DeFi/assets/123862185/a9bd034b-b9e7-4219-a17a-f942739be1d7">

- Expect Result
Should be always the same.

**Comment by arealclimber** [comment]
- [ ]  按星星之後應立即顯示效果
- [ ]  這次追蹤/取消追蹤的紀錄，應該在下次重開網站的時候顯示
    - [ ]  檢查是否實作 cookie

**Comment by arealclimber** [comment]
taking 4 hrs

**Comment by arealclimber** [comment]
https://github.com/CAFECA-IO/TideBit-DeFi/issues/1329
