### ISSUE TITLE
[BUG] i18 link error in common.js

### ISSUE THREAD

**Issue by RexBearIU** [CAFECA-IO/TideBit-DeFi#1290]
- Environment Description
  - Machine: MacBook Pro (13-inch, 2017, Two Thunderbolt 3 ports)
  - OS version: macOS Ventura 13.5.2（22G91）
  - Browser version: Microsoft Edge v116.0.1938.76
- How to reproduce
open the landing page
- Current Result
<img width="591" alt="截圖 2023-10-02 下午5 42 53" src="https://github.com/CAFECA-IO/TideBit-DeFi/assets/123862185/02de5882-1190-463a-925d-cb12c68f4866">
<img width="900" alt="截圖 2023-10-02 下午5 43 09" src="https://github.com/CAFECA-IO/TideBit-DeFi/assets/123862185/b6206f0e-06c5-422e-a30b-d35ff9f186ad">

- Expect Result
Should be the same.

**Comment by arealclimber** [comment]
taking 0.5 hrs
