### ISSUE TITLE
[BUG] Leaderboard UI error

### ISSUE THREAD

**Issue by RexBearIU** [CAFECA-IO/TideBit-DeFi#1298]
- Environment Description
  - Machine: MacBook Pro (13-inch, 2017, Two Thunderbolt 3 ports)
  - OS version: macOS Ventura 13.5.2（22G91）
  - Browser version: Chromium 117.0.5938.62 (開發人員版本) (x86_64)
- How to reproduce
Use Playwright to do the automation test
- Current Result
![截圖 2023-10-03 上午11 47 55](https://github.com/CAFECA-IO/TideBit-DeFi/assets/123862185/4a58186f-23f3-49b8-99dd-5d8cefde0c60)

- Expect Result
<img width="567" alt="截圖 2023-10-03 上午11 51 30" src="https://github.com/CAFECA-IO/TideBit-DeFi/assets/123862185/20805159-621d-49d7-8184-16ba74e33336">

**Comment by RexBearIU** [comment]
Use headless mode can work sometimes, but still too slow to load the date.

**Comment by Julian0701** [comment]
- take 4 hrs
- 等待分支合併後驗證

**Comment by RexBearIU** [comment]
It takes 1 hour to fix the playwright test, the solution is to wait for the live time.
