### ISSUE TITLE
[BUG] CFD trade position live chart lag

### ISSUE THREAD

**Issue by RexBearIU** [CAFECA-IO/TideBit-DeFi#1306]
- Environment Description
  - Machine: MacBook Pro (13-inch, 2017, Two Thunderbolt 3 ports)
  - OS version: macOS Ventura 13.5.2（22G91）
  - Browser version: Chromium 117.0.5938.62 (開發人員版本) (x86_64)
- How to reproduce
Open CFD trade page with 10+ position
- Current Result
too many position live charts cause browser lag.

<img width="253" alt="截圖 2023-10-04 上午11 39 50" src="https://github.com/CAFECA-IO/TideBit-DeFi/assets/123862185/ca1a3bbf-8b64-4ef0-ad18-61770955229d">

- Expect Result
It should be more smooth for users to use.

**Comment by arealclimber** [comment]
- [ ] 折線圖不更新

**Comment by arealclimber** [comment]
taking 1 hr
