### ISSUE TITLE
[BUG] Header PNL plus and minus signs are wrong.

### ISSUE THREAD

**Issue by RexBearIU** [CAFECA-IO/TideBit-DeFi#1316]
- Environment Description
  - Machine: MacBook Pro (13-inch, 2017, Two Thunderbolt 3 ports)
  - OS version: macOS Ventura 13.5.2（22G91）
  - Browser version: Chromium 117.0.5938.62 (開發人員版本) (x86_64)
- How to reproduce
Open My asset page
- Current Result
PNL plus and minus signs are different.
![截圖 2023-10-06 下午6 43 00](https://github.com/CAFECA-IO/TideBit-DeFi/assets/123862185/50c3beb3-50ba-46d7-a929-ea68fadeb23e)

- Expect Result
It should be the same.

**Comment by Julian0701** [comment]
- take 0.5 hr
