### ISSUE TITLE
notification toast 

### ISSUE THREAD

**Issue by arealclimber** [CAFECA-IO/TideBit-DeFi#132]
- [x] toast style
- [x] data from Context

**Comment by Julian0701** [comment]
ref
https://ithelp.ithome.com.tw/articles/10280998
https://www.youtube.com/watch?v=VdVGPov7Yqc
https://blog.logrocket.com/using-react-toastify-style-toast-messages/

**Comment by Julian0701** [comment]
- take 3.5 hrs

完成樣式調整

**Comment by Julian0701** [comment]
- take 3.5 hrs

樣式調整完成
