### ISSUE TITLE
[BUG] CFD close position price error

### ISSUE THREAD

**Issue by RexBearIU** [CAFECA-IO/TideBit-DeFi#1323]
- Environment Description
  - Machine: MacBook Pro (13-inch, 2017, Two Thunderbolt 3 ports)
  - OS version: macOS Ventura 13.5.2（22G91）
  - Browser version: Chromium 117.0.5938.62 (開發人員版本) (x86_64)
- How to reproduce
Open My asset page
- Current Result
The close price is 0.
![Screenshot 2023-10-11 at 5 58 38 PM](https://github.com/CAFECA-IO/TideBit-DeFi/assets/123862185/3fce5614-b535-46a8-83b7-8e3e3032f602)
![Screenshot 2023-10-11 at 5 59 17 PM](https://github.com/CAFECA-IO/TideBit-DeFi/assets/123862185/fcb6b9cf-0d08-4208-a553-aaa8f3e2ac07)

- Expect Result
It should have number.

**Comment by Julian0701** [comment]
- take 1 hr
