### ISSUE TITLE
[BUG] Leaderboard time error

### ISSUE THREAD

**Issue by RexBearIU** [CAFECA-IO/TideBit-DeFi#1324]
- Environment Description
  - Machine: MacBook Pro (13-inch, 2017, Two Thunderbolt 3 ports)
  - OS version: macOS Ventura 13.5.2（22G91）
  - Browser version: Chromium 117.0.5938.62 (開發人員版本) (x86_64)
- How to reproduce
Playwright test in github action compare to locale test
- Current Result
Today should be 2023-10-11. The end of last week should be 2023-10-07 according to API, but it shows 2023-20-08 in local.

<img width="359" alt="截圖 2023-10-12 上午9 23 11" src="https://github.com/CAFECA-IO/TideBit-DeFi/assets/123862185/7290903c-a8cf-4e6a-989b-493b0d0b80b5">

![截圖 2023-10-12 上午9 24 46](https://github.com/CAFECA-IO/TideBit-DeFi/assets/123862185/ed00cd8e-db62-4de0-8f5d-296abe4e6a9f)

![截圖 2023-10-12 上午9 25 44](https://github.com/CAFECA-IO/TideBit-DeFi/assets/123862185/f71e2cd4-4dbb-4f5d-a237-640535f311ce)

- Expect Result
It should be the same.

**Comment by Julian0701** [comment]
- take 3 hrs
