### ISSUE TITLE
[BUG] Header notification layer and profile layer overlap

### ISSUE THREAD

**Issue by RexBearIU** [CAFECA-IO/TideBit-DeFi#1335]
- Environment Description
  - Machine: MacBook Pro (13-inch, 2017, Two Thunderbolt 3 ports)
  - OS version: macOS Ventura 13.5.2（22G91）
  - Browser version: Chromium 117.0.5938.62 (開發人員版本) (x86_64)
- How to reproduce
open tidebit defi in mobile mode
- Current Result

![截圖 2023-10-13 下午5 20 15](https://github.com/CAFECA-IO/TideBit-DeFi/assets/123862185/575de422-c720-4fd7-a720-55399aad5bb5)
![截圖 2023-10-13 下午5 20 29](https://github.com/CAFECA-IO/TideBit-DeFi/assets/123862185/2e16fb18-2f09-41f7-8863-bba5d8a09628)

- Expect Result
It should not overlap.

**Comment by Julian0701** [comment]
- take 4 hrs
- 調整 notification item 樣式
