### ISSUE TITLE
[BUG] My asset position error

### ISSUE THREAD

**Issue by RexBearIU** [CAFECA-IO/TideBit-DeFi#1336]
- Environment Description
  - Machine: MacBook Pro (13-inch, 2017, Two Thunderbolt 3 ports)
  - OS version: macOS Ventura 13.5.2（22G91）
  - Browser version: Chromium 117.0.5938.62 (開發人員版本) (x86_64)
- How to reproduce
Playwright test in github action compare to locale test
- Current Result
- 從 My Asset 中查看還開著的倉位會讀不到PNL的資料

<img width="400" alt="Screenshot 2023-10-13 at 4 34 10 PM" src="https://github.com/CAFECA-IO/TideBit-DeFi/assets/98379087/9023fd94-fe9c-4153-a229-2d21f07c9588">

- Expect Result
It should have PNL.

_Originally posted by @JodieWu in https://github.com/CAFECA-IO/TideBit-DeFi/issues/1320#issuecomment-1761135287_

**Comment by Julian0701** [comment]
- take 0.5 hr
