### ISSUE TITLE
[BUG] CFD Trade close position price error

### ISSUE THREAD

**Issue by RexBearIU** [CAFECA-IO/TideBit-DeFi#1338]
- Environment Description
  - Machine: MacBook Pro (13-inch, 2017, Two Thunderbolt 3 ports)
  - OS version: macOS Ventura 13.5.2（22G91）
  - Browser version: Chromium 117.0.5938.62 (開發人員版本) (x86_64)
- How to reproduce
Open a position with two decimal places.
- Current Result
open a 0.5 amount position will become 0.51
![Screenshot 2023-10-13 at 4 21 02 PM](https://github.com/CAFECA-IO/TideBit-DeFi/assets/123862185/f8d9aa27-ff3f-43b2-b9a6-7d15eb16a51f)

![Screenshot 2023-10-13 at 4 24 34 PM](https://github.com/CAFECA-IO/TideBit-DeFi/assets/123862185/c02c7657-0216-494a-8376-0e25ad63cf96)

![Screenshot 2023-10-13 at 4 19 21 PM](https://github.com/CAFECA-IO/TideBit-DeFi/assets/123862185/5ed42d88-7447-4232-9b03-b289923d48d5)

- Expect Result
It should be the same.

**Comment by arealclimber** [comment]
taking 1 hr

**Comment by arealclimber** [comment]
remaining 0.5 hrs

**Comment by arealclimber** [comment]
taking 0.5 hrs
