### ISSUE TITLE
[BUG] CFD Trade pages display error

### ISSUE THREAD

**Issue by RexBearIU** [CAFECA-IO/TideBit-DeFi#1341]
- Environment Description
  - Machine: MacBook Pro (13-inch, 2017, Two Thunderbolt 3 ports)
  - OS version: macOS Ventura 13.5.2（22G91）
  - Browser version: Chromium 117.0.5938.62 (開發人員版本) (x86_64)
- How to reproduce
Open CFD trade page 
- Current Result
Candlestick and open position can't get data to show
![截圖 2023-10-16 下午1 41 08](https://github.com/CAFECA-IO/TideBit-DeFi/assets/123862185/65b77c69-02ea-47b2-9a4f-610d6150f085)

- Expect Result
It should display sucessfully.

**Comment by RexBearIU** [comment]
It was surprisingly fixed. need to keep tracking

**Comment by arealclimber** [comment]
當時後端進行調整，前端無法拿到 API 資料

<img width="415" alt="image" src="https://github.com/CAFECA-IO/TideBit-DeFi/assets/20677913/2e204e66-55fb-4b9f-95e8-cbf6647f8184">

**Comment by arealclimber** [comment]
當時後端進行調整，前端無法拿到 API 資料；當時登出後重新整理 Trade Tab 應該會顯示暫停交易 

<img width="415" alt="image" src="https://github.com/CAFECA-IO/TideBit-DeFi/assets/20677913/2e204e66-55fb-4b9f-95e8-cbf6647f8184">

**Comment by RexBearIU** [comment]
Did not appear again.
