### ISSUE TITLE
[BUG] Header layout error

### ISSUE THREAD

**Issue by RexBearIU** [CAFECA-IO/TideBit-DeFi#1349]
- Environment Description
  - Machine: MacBook Pro (13-inch, 2017, Two Thunderbolt 3 ports)
  - OS version: macOS Ventura 13.5.2（22G91）
  - Browser version: Chromium 117.0.5938.62 (開發人員版本) (x86_64)
- How to reproduce
Open landing page
- Current Result
It only happen when your are rich enough.
![image](https://github.com/CAFECA-IO/TideBit-DeFi/assets/123862185/e75a22b7-d452-4562-be38-3d904b2953d1)

- Expect Result
It should not overlap.

**Comment by Julian0701** [comment]
- take 1 hr
