### ISSUE TITLE
根據 Lighthouse 指標優化 TBD (1/2)

### ISSUE THREAD

**Issue by arealclimber** [CAFECA-IO/TideBit-DeFi#1435]
根據 extension 或 dev tool 內建的 Lighthouse report 優化 TBD 網站

**Comment by Julian0701** [comment]
實際做法：調整首頁 div 結構、移除不必要的 css

![image](https://github.com/CAFECA-IO/TideBit-DeFi/assets/114177573/d4159357-aefa-4add-bd2a-6e9fb11113c8)

![image](https://github.com/CAFECA-IO/TideBit-DeFi/assets/114177573/3cf03b8e-26ea-4753-a01e-6c91c171322d)

**Performance** 30 -> 65
**Accessibility** 89 -> 94 
**Best Practices** 95 -> 95
**SEO** 82 -> 80

- take 8 hrs
- continue to #1479 
- 需調查 SEO 減少的原因
