### ISSUE TITLE
NavBar RWD

### ISSUE THREAD

**Issue by arealclimber** [CAFECA-IO/TideBit-DeFi#2]
TideBit DeFi [Mockup](https://xd.adobe.com/view/920d36bd-2d1a-4edd-8a2a-824445f1d3b0-c75e/?fullscreen&hints=off)中的RWD NavBar

- [x] init Next.js and Tailwind CSS
- [x] Icons to be implemented
- [x] NavBar RWD to be improved

**Comment by arealclimber** [comment]
taking 1 hrs

remaining 1 hrs
- [x] init Next.js and Tailwind CSS
- [ ] Icons to be implemented
- [ ] NavBar RWD to be improved

**Comment by arealclimber** [comment]
taking 1 hr

**Comment by Luphia** [comment]
remain issues
- mobile version
- menu position

**Comment by arealclimber** [comment]
taking 8 hrs

**Comment by arealclimber** [comment]
taking 2 hrs

**Comment by arealclimber** [comment]
- [ ] logo
- [ ] version

**Comment by arealclimber** [comment]
taking 0.5 hrs

remaining 0.5 hrs
- [ ] logo

**Comment by arealclimber** [comment]
taking 0.5 hrs
