### ISSUE TITLE
Loading Modal 縮小功能

### ISSUE THREAD

**Issue by arealclimber** [CAFECA-IO/TideBit-DeFi#213]
- [x] 縮小 Loading modal 要顯示 toast
  - [x] 實驗寫在 GlobalContext 或寫在 LoadingModal
- [x] 在登入過程中，在用戶選錢包之前縮小 loading ，需要能夠接著 pop up 之後流程的 modals
- [x] [Loading modal 須被控制是否顯示縮小按鈕 ](https://xd.adobe.com/view/b4bc1f81-78f4-4de9-979f-20cb0d457d70-e1ef/screen/e453de9a-c90c-4034-b52c-bbc5ee383d40/)

**Comment by Julian0701** [comment]
- take 4 hrs 
- 考慮到 type text 需要帶 i18n ，決定把 toast 縮小的功能寫在 Loading modal 裡

<img width="632" alt="image" src="https://user-images.githubusercontent.com/114177573/233965457-65aef752-9075-4eff-9cca-07703b7dc489.png">
- 調整後的 IToastify

<img width="586" alt="image" src="https://user-images.githubusercontent.com/114177573/233965719-9d321a23-ece0-4805-ab73-d901fea67c6d.png">
- 調整後的 IProcessDataModal

- remain 2 hrs

**Comment by Julian0701** [comment]
- 錢包連線時不提供縮小 modal 的功能，以免發生問題
- 目前可以縮小成 toast 的只有 deposit 和 withdraw
- take 1 hr
