### ISSUE TITLE
[enhance] TBD 介面優化

### ISSUE THREAD

**Issue by JodieWu** [CAFECA-IO/TideBit-DeFi#218]
- 統一 fail caption 位置
- 新增 TideBit HK 連結失敗畫面
- Add to favorite before login
- News date
- Position price and time 
- Position price 保留 15 秒
- Position update 關倉位置調整
- 關倉/ 更新倉位看不出是哪一張票
- 設定止盈止損協助計算損失/營收

**Comment by JodieWu** [comment]
完成時間：4 hr
https://xd.adobe.com/view/920d36bd-2d1a-4edd-8a2a-824445f1d3b0-c75e/screen/1efeff4c-2c35-4644-aa82-40fd9e9bf9fe/specs/

**Comment by arealclimber** [comment]
- [ ]  my assets page 的 PnL 的上漲下跌符號

**Comment by JodieWu** [comment]
鍵盤輸入 ▴ ▾
