### ISSUE TITLE
行動版設計稿的更新倉位確認視窗

### ISSUE THREAD

**Issue by arealclimber** [CAFECA-IO/TideBit-DeFi#221]
- [x] [行動版設計稿](https://xd.adobe.com/view/b4bc1f81-78f4-4de9-979f-20cb0d457d70-e1ef/grid)的更新倉位確認視窗

電腦版: ![image](https://user-images.githubusercontent.com/20677913/218651137-81f4e668-3db8-4d82-b610-5c63fe752994.png)

**Comment by JodieWu** [comment]
https://xd.adobe.com/view/b4bc1f81-78f4-4de9-979f-20cb0d457d70-e1ef/screen/e453de9a-c90c-4034-b52c-bbc5ee383d40/

https://xd.adobe.com/view/b4bc1f81-78f4-4de9-979f-20cb0d457d70-e1ef/screen/db92b77c-24da-4a47-88f4-45c46312b288/

https://xd.adobe.com/view/b4bc1f81-78f4-4de9-979f-20cb0d457d70-e1ef/screen/8035bf2f-325e-4029-97aa-de21c9321144/

**Comment by Luphia** [comment]
- already have design document

**Comment by Luphia** [comment]
- open position with title: TBDMMK-000024
- update position with title: TBDMMK-000116
- close position with title: TBDMMK-000025
