### ISSUE TITLE
Notification and its item enhancement

### ISSUE THREAD

**Issue by arealclimber** [CAFECA-IO/TideBit-DeFi#232]
- [x]  Notification 如果是 0 ，整個數字框框要消失
- [x]  Notification item 要 cursor-pointer ，點了要消失，要有消失動畫，也要有下面的 item 往上補的動畫
- transition

**Comment by Julian0701** [comment]
- take 4 hrs

須先處理 #564

**Comment by Julian0701** [comment]
- take 2 hrs

remain readAll animation

**Comment by Julian0701** [comment]
- take 1 hr
