### ISSUE TITLE
My assets - ReceiptList

### ISSUE THREAD

**Issue by arealclimber** [CAFECA-IO/TideBit-DeFi#241]
- Spec: [Desktop](https://xd.adobe.com/view/b4bc1f81-78f4-4de9-979f-20cb0d457d70-e1ef/screen/0e723a17-64dd-4374-a15e-2c7044108592/specs/) / [Mobile](https://xd.adobe.com/view/b4bc1f81-78f4-4de9-979f-20cb0d457d70-e1ef/screen/0e723a17-64dd-4374-a15e-2c7044108592/)

**Comment by Julian0701** [comment]
已在 #290 完成
