### ISSUE TITLE
My asset - Datepicker

### ISSUE THREAD

**Issue by arealclimber** [CAFECA-IO/TideBit-DeFi#242]
Ref: 
- 設計稿
  - [TideBit DeFi 設計稿電腦版 Spec](https://xd.adobe.com/view/920d36bd-2d1a-4edd-8a2a-824445f1d3b0-c75e/grid)
  - [TideBit DeFi 設計稿手機版 Spec](https://xd.adobe.com/view/b4bc1f81-78f4-4de9-979f-20cb0d457d70-e1ef/grid)
- Sequence Diagram
  - [Sequence Diagram 001 (interaction between user, frontend and backend)](https://github.com/CAFECA-IO/Documents/blob/main/TBD/TBDSD00001.md)
  - [Sequence Diagram 002 (background mechanism)](https://github.com/CAFECA-IO/Documents/blob/main/TBD/TBDSD00002.md)
- Diagrams 
  - [Global context document](https://soul-quenching.notion.site/Global-Context-d93ac7c941c94fb6b173d34a7bc4e959) 
  - [Table of interface](https://github.com/CAFECA-IO/EventReport/blob/main/meeting/20230106_tbd_mvp.md) 
  - [Component Diagram](https://github.com/CAFECA-IO/Documents/blob/main/TBD/TBDCP00001.md)
  - [Class Diagram](https://github.com/CAFECA-IO/Documents/blob/main/TBD/TBDCD00001.md)
  - [Use Cases Diagram](https://github.com/CAFECA-IO/Documents/blob/main/TBD/TBDUC00001.md)

**Comment by Julian0701** [comment]
take 2 hrs

remain 
- dateUpdateHandler

**Comment by Julian0701** [comment]
take 2 hrs

**Comment by Julian0701** [comment]
- take 2.5 hrs

remain 
1. 選到的日期要有藍色圓圈
2. PopulateDates props type

**Comment by Julian0701** [comment]
done

- take 2.5 hrs
