### ISSUE TITLE
[Bug] ApexOptions

### ISSUE THREAD

**Issue by arealclimber** [CAFECA-IO/TideBit-DeFi#267]
- 更新 apexcharts 並調整 ApexOptions 格式
- Ref
  - https://github.com/apexcharts/apexcharts.js/issues/3646
  - [Doc](https://apexcharts.com/docs/options/annotations/)
  - [GitHub release](https://github.com/apexcharts/apexcharts.js/releases)
  - [NPM](https://www.npmjs.com/package/apexcharts)

**Comment by arealclimber** [comment]
taking 1 hr

**Comment by canblt** [comment]
dosnt change anything  https://github.com/apexcharts/apexcharts.js/issues/3646

Link: https://codesandbox.io/s/react-basic-example-forked-fd0is9
