### ISSUE TITLE
`SignTypedData` by walletconnect

### ISSUE THREAD

**Issue by arealclimber** [CAFECA-IO/TideBit-DeFi#27]
- [x] Jest to test if it works

參考文件: [Raw Transaction](https://github.com/CAFECA-IO/TideBit-DeFi/wiki/Raw-Transaction)

**Comment by arealclimber** [comment]
taking 1 hrs

**Comment by arealclimber** [comment]
taking 5 hrs
在 Luphia 幫助下完成
- wallet connect 應在連接錢包後 跳出 signature 視窗 但還是在`useEffect`裡面

remaining 5 hrs

**Comment by arealclimber** [comment]
taking 6 hrs

**Comment by arealclimber** [comment]
remaining 3 hrs
- [ ] 偵測metamask錢包內斷線，並清乾淨，檢查metamask跟wallet connect的連接跟簽名邏輯

**Comment by arealclimber** [comment]
taking 4.5 hrs
remaining 3 hrs
- [ ] wallet connect 跟 metamask 切換錢包應該再送一次簽名

**Comment by arealclimber** [comment]
taking 10 hrs
現在metamask 擴充錢包連上不會送兩次錢包，但切換錢包也不會送簽名了，總之wallet connect跟metamask越來越多蟲了
remaining 10 hrs
- [ ] wallet connect - imToken 
`wallet connect sign failure:  Exceed the task queue limit.`
會傳送簽名要求但會先顯示失敗，但有時候不會出現該錯誤,需檢查在哪個地方重複送簽名
- [ ] injected metamask remove listener
- [ ] 沒簽名就disconnect，沒簽名就不算登入

**Comment by Luphia** [comment]
- work with userContext
