### ISSUE TITLE
leaderboard page -前三名

### ISSUE THREAD

**Issue by arealclimber** [CAFECA-IO/TideBit-DeFi#280]
Ref
- [Desktop](https://xd.adobe.com/view/920d36bd-2d1a-4edd-8a2a-824445f1d3b0-c75e/screen/9440d16f-f577-4b00-ace1-6740d65fb9d6)
- [Mobile](https://xd.adobe.com/view/b4bc1f81-78f4-4de9-979f-20cb0d457d70-e1ef/screen/7f85e214-4a0e-4217-859c-9c4d2d60ec42/specs/)

**Comment by Julian0701** [comment]
- take 5 hrs

remain 
- avatar size RWD
- get data from Context
- 將 top 3 list 寫成迴圈

**Comment by Julian0701** [comment]
- take 3 hrs

remain 
- get data from context

**Comment by Julian0701** [comment]
- take 2 hrs
