### ISSUE TITLE
personal badge

### ISSUE THREAD

**Issue by arealclimber** [CAFECA-IO/TideBit-DeFi#281]
Ref
- [Desktop](https://xd.adobe.com/view/920d36bd-2d1a-4edd-8a2a-824445f1d3b0-c75e/screen/f5ec171f-f85f-4b63-a859-b78365e72e39/)
- [Mobile](https://xd.adobe.com/view/b4bc1f81-78f4-4de9-979f-20cb0d457d70-e1ef/screen/225585a5-3af1-4086-ab80-a37c9a23d42a/specs/)

**Comment by Julian0701** [comment]
- take 4 hrs

remain 4 hrs
- 整理 IPersonalInfoModal
- Badges parts
- i18n

**Comment by Julian0701** [comment]
- take 8 hrs

remain 5 hrs
- dataPersonalInfoModalHandler 取得資料的方法
- 獲得的徽章要亮起來
- 排行榜的用戶也要串上 Personal Info Modal

**Comment by Julian0701** [comment]
- take 5.5 hrs

done
