### ISSUE TITLE
badge box

### ISSUE THREAD

**Issue by arealclimber** [CAFECA-IO/TideBit-DeFi#283]
用戶獲得的徽章列表
[Ref](https://xd.adobe.com/view/920d36bd-2d1a-4edd-8a2a-824445f1d3b0-c75e/screen/f742af97-e6aa-4b95-bb06-623e97c40e71/)

**Comment by Julian0701** [comment]
take 2.5 hrs

remain 2.5 hrs
- [ ] get data from context
- [ ] i18n

**Comment by Julian0701** [comment]
- take 2.5 hrs

**Comment by Julian0701** [comment]
remain
- 顯示獲得時間
- 分享功能
