### ISSUE TITLE
My assets - ReceiptSearch

### ISSUE THREAD

**Issue by arealclimber** [CAFECA-IO/TideBit-DeFi#289]
- Spec: [Desktop](https://xd.adobe.com/view/920d36bd-2d1a-4edd-8a2a-824445f1d3b0-c75e/screen/e1ca1303-62e1-43e5-bb93-15364305a9b9/) / [Mobile](https://xd.adobe.com/view/b4bc1f81-78f4-4de9-979f-20cb0d457d70-e1ef/screen/0e723a17-64dd-4374-a15e-2c7044108592/)

**Comment by Julian0701** [comment]
take 4 hrs
- 完成排版

remain
- date picker
- 搜尋功能

**Comment by Julian0701** [comment]
take 2 hrs
- date picker 排版

remain 
- 功能串接

**Comment by Julian0701** [comment]
- take 1 hr
完成 Trading Type 過濾器

**Comment by Julian0701** [comment]
- take 3 hrs

完成關鍵字搜尋

**Comment by Julian0701** [comment]
- take 1.5 hrs
 
完成日期搜尋
