### ISSUE TITLE
My assets - ReceiptItem

### ISSUE THREAD

**Issue by arealclimber** [CAFECA-IO/TideBit-DeFi#290]
- Spec: [Desktop](https://xd.adobe.com/view/920d36bd-2d1a-4edd-8a2a-824445f1d3b0-c75e/screen/e1ca1303-62e1-43e5-bb93-15364305a9b9/) / [Mobile](https://xd.adobe.com/view/b4bc1f81-78f4-4de9-979f-20cb0d457d70-e1ef/screen/0e723a17-64dd-4374-a15e-2c7044108592/)

**Comment by Julian0701** [comment]
take 4 hrs
- 完成排版

remain
- button click handler

**Comment by Julian0701** [comment]
1. IOrder 需要 ?available 、 ?detail
2. Receipt Button 的顏色用 IOrder 的 dummyData targetAmount 決定，所以要有正有負
3. ReceiptList 按月份呈現資料

**Comment by Julian0701** [comment]
take 1 hr ，完成
- 調整 IOrder interface
- Button 顏色由 targetAmount 決定

**Comment by Julian0701** [comment]
take 2 hrs
- ReceiptList 按月份呈現資料

**Comment by Julian0701** [comment]
take 2 hrs
- IOrder 已更新
- 加入 dummyClosedCFDOrder

**Comment by Julian0701** [comment]
- take 1 hr

remain 2 hrs
- 用 txid 到 UserContext 拿資料，再用 globalContext 叫出 detail modal

**Comment by Julian0701** [comment]
- take 2 hrs

remain 

- [ ] - deposit history modal
- [ ] - withdraw history modal
