### ISSUE TITLE
leaderboard page - live/daily/weekly/monthly

### ISSUE THREAD

**Issue by arealclimber** [CAFECA-IO/TideBit-DeFi#291]
[Desktop](https://xd.adobe.com/view/920d36bd-2d1a-4edd-8a2a-824445f1d3b0-c75e/screen/9440d16f-f577-4b00-ace1-6740d65fb9d6/)/[mobile](https://xd.adobe.com/view/b4bc1f81-78f4-4de9-979f-20cb0d457d70-e1ef/screen/7f85e214-4a0e-4217-859c-9c4d2d60ec42/specs/)

**Comment by Julian0701** [comment]
- take 5 hrs
