### ISSUE TITLE
leaderboard page - 用戶個人排名

### ISSUE THREAD

**Issue by arealclimber** [CAFECA-IO/TideBit-DeFi#292]
Ref:

- [Desktop](https://xd.adobe.com/view/920d36bd-2d1a-4edd-8a2a-824445f1d3b0-c75e/screen/f5ec171f-f85f-4b63-a859-b78365e72e39/)
- [Mobile](https://xd.adobe.com/view/b4bc1f81-78f4-4de9-979f-20cb0d457d70-e1ef/screen/7f85e214-4a0e-4217-859c-9c4d2d60ec42/specs/)

**Comment by Julian0701** [comment]
- take 5 hrs

remain 
- get data from context
- default arrow icon

**Comment by Julian0701** [comment]
- take 2 hrs
- done

**Comment by Julian0701** [comment]
- take 7 hrs
done
