### ISSUE TITLE
No ticker list data in landing page

### ISSUE THREAD

**Issue by Luphia** [CAFECA-IO/TideBit-DeFi#300]
<img width="1488" alt="截圖 2023-03-03 下午12 35 00" src="https://user-images.githubusercontent.com/270062/222632740-9037b056-8930-42d8-8a6d-5b7321753c79.png">

**Comment by TzuHanLiang** [comment]
- take 0.5hrs，確認 tickers 最新資料是有拿到，也有觸發畫面重畫，可能是畫面 re-render 有問題

**Comment by arealclimber** [comment]
taking 1 hr
- 用 `useEffect + useState + marketCtx.listAvailableTickers()`，正確顯示交易對行情信息
