### ISSUE TITLE
System can not work if socket.io connection is not available

### ISSUE THREAD

**Issue by Luphia** [CAFECA-IO/TideBit-DeFi#301]
<img width="1493" alt="截圖 2023-03-03 下午12 36 24" src="https://user-images.githubusercontent.com/270062/222633072-2cf07b5b-c994-47c7-acb0-3c08ed068769.png">

**Comment by TzuHanLiang** [comment]
- take 0.5hrs： 試使用 catch 沒有接到 error，需要重新評估問題原因

**Comment by TzuHanLiang** [comment]
- 系統不能 work 除了 socket.io connection is not available ，主要是因為沒有設定 `Access-Control-Allow-Origin`
