### ISSUE TITLE
Failed modal 樣式調整

### ISSUE THREAD

**Issue by arealclimber** [CAFECA-IO/TideBit-DeFi#446]
[設計](https://xd.adobe.com/view/b4bc1f81-78f4-4de9-979f-20cb0d457d70-e1ef/screen/0a653562-bc58-4fe4-bee4-97b6a5a54c2f/)

**Comment by Julian0701** [comment]
- take 1.5 hrs

**Comment by Julian0701** [comment]
沒有 failedMsg 的話，紅格子不用顯示

**Comment by Julian0701** [comment]
- take 0.5 hr

修改完成
