### ISSUE TITLE
Avatar menu

### ISSUE THREAD

**Issue by arealclimber** [CAFECA-IO/TideBit-DeFi#48]
- [x] icon 補上
- [x] 電腦版的動畫
- [x] 行動版的動畫

- [TideBit DeFi 設計稿電腦版 Spec](https://xd.adobe.com/view/920d36bd-2d1a-4edd-8a2a-824445f1d3b0-c75e/specs/)
- [TideBit DeFi 設計稿手機版 Spec](https://xd.adobe.com/view/b4bc1f81-78f4-4de9-979f-20cb0d457d70-e1ef/)

**Comment by arealclimber** [comment]
taking 1 hr
remaining 2 hrs

**Comment by Julian0701** [comment]
- take 2 hrs

- remain 行動版漸入漸出動畫

**Comment by Julian0701** [comment]
- take 1 hr

動畫完成
