### ISSUE TITLE
行動版NavBar

### ISSUE THREAD

**Issue by arealclimber** [CAFECA-IO/TideBit-DeFi#50]
- [ ] notification 數字的位置
- [x] 涵蓋整個螢幕的menu
- [ ] 排版
- [ ] 動畫
- [x] mobile navbar full screen and i18n text
- [TideBit DeFi 設計稿電腦版 Spec](https://xd.adobe.com/view/920d36bd-2d1a-4edd-8a2a-824445f1d3b0-c75e/specs/)
- [TideBit DeFi 設計稿手機版 Spec](https://xd.adobe.com/view/b4bc1f81-78f4-4de9-979f-20cb0d457d70-e1ef/)

**Comment by arealclimber** [comment]
taking 0.5 hr
remaing 2.5 hrs

**Comment by Julian0701** [comment]
- migrate to [#146](https://github.com/CAFECA-IO/TideBit-DeFi/issues/146)
