### ISSUE TITLE
行動版通知欄

### ISSUE THREAD

**Issue by arealclimber** [CAFECA-IO/TideBit-DeFi#51]
- [TideBit DeFi 設計稿電腦版 Spec](https://xd.adobe.com/view/920d36bd-2d1a-4edd-8a2a-824445f1d3b0-c75e/specs/)
- [TideBit DeFi 設計稿手機版 Spec](https://xd.adobe.com/view/b4bc1f81-78f4-4de9-979f-20cb0d457d70-e1ef/)

**Comment by Julian0701** [comment]
- take 2 hrs
  - 調整 layout
- remain
  - 製作 mobile notification  list
  - 調整 NotificationItem

**Comment by Julian0701** [comment]
- take 4 hrs
  - 完成 行動版 Notification 、調整 NotificationItem

**Comment by Julian0701** [comment]
- remain 通知欄無法捲到最下面
   - 把 fixed 改成 absolute
   - 調整 height

**Comment by Julian0701** [comment]
- take 0.5 hr
