### ISSUE TITLE
[Enhance] TBD 介面優化

### ISSUE THREAD

**Issue by JodieWu** [CAFECA-IO/TideBit-DeFi#514]
- [x] 排行榜規則提示
- [x] 新增交易紀錄下載功能
- [x] 三種資產儲備率
- [x] 審計報告下載
- [x] Beta Test Mark

**Comment by JodieWu** [comment]
完成時間： 3 hr
https://xd.adobe.com/view/920d36bd-2d1a-4edd-8a2a-824445f1d3b0-c75e/

**Comment by Luphia** [comment]
- 首頁需補充一個區塊 Latest AI Audit Report
  - 審計時間
  - 每份報告由 ICON 呈現
  - power by BOLT（連至 boltchain.io）
