### ISSUE TITLE
首頁的 volume/users/fee 資料來自 context

### ISSUE THREAD

**Issue by arealclimber** [CAFECA-IO/TideBit-DeFi#545]
把 fee 改成其他資料，不顯示 fee

**Comment by Julian0701** [comment]
<img width="687" alt="image" src="https://user-images.githubusercontent.com/114177573/232999965-60e29696-5cbf-4f77-a5fc-f2fb5ba81c9f.png">

- 將手續費改成累積成交量 (VA)

<img width="726" alt="image" src="https://user-images.githubusercontent.com/114177573/233000367-c16fc189-5c0f-42f4-a944-05088c1de93a.png">

- 在 marketCtx 塞入 dummyData

- take 3 hrs
