### ISSUE TITLE
my asset - PnL 資料來自 context

### ISSUE THREAD

**Issue by arealclimber** [CAFECA-IO/TideBit-DeFi#546]
在 userContext 取得用戶的 PnL 資料

![image](https://user-images.githubusercontent.com/114177573/233311155-ff09a801-ae96-4210-b5f6-b785007614c5.png)

- pnl_section.tsx

**Comment by Julian0701** [comment]
- take 1.5 hrs

需將 balance section 和 interest section 的資料一起整合在一個 getMyAssets 的 function

- remain 1 hrs
