### ISSUE TITLE
Trading Page - 切換 ticker 後畫面會卡頓

### ISSUE THREAD

**Issue by Julian0701** [CAFECA-IO/TideBit-DeFi#719]
### 判斷造成的原因為 tradebook
1. tradebook 中的 trades 及 predictTrades 沒有拆分不同 ticker 保存 trades 資料，所以在切換 ticker 時會混到 trades資，且會直接將資料加進去，沒有做 data cleaning
2. 沒有清除過久的資料

### 解決方法
1. 新增 addTrades 方法
    1. 切換 ticker 時，拿到 api 資料後會，將  trades 及 predictTrades 清空 
    2. clearPredictionLoop
    3. 資料新增完後 startPredictionLoop
2. 新增 _trim 方法
    1. 判斷第一筆資料的創建時間小於需要被保存的時間為是的話
    2. 使用 filter  保留 15 分鐘內的資料 
    3. 使用 reduce  remove duplicate tradeId
    4. 使用 sort 將資料根據 tradeId 排序

**Comment by TzuHanLiang** [comment]
- take 3hrs
