### ISSUE TITLE
[BUG] trade tab 和 position open modal 的點差不一致

### ISSUE THREAD

**Issue by Julian0701** [CAFECA-IO/TideBit-DeFi#721]
![image](https://github.com/CAFECA-IO/TideBit-DeFi/assets/114177573/39dd9da1-17dd-49e5-9019-c47ffa8aa17b)

![image](https://github.com/CAFECA-IO/TideBit-DeFi/assets/114177573/965bb2a4-2558-42f9-af3a-3d789de848ea)

**Comment by arealclimber** [comment]
已被 @TzuHanLiang 解決

![image](https://github.com/CAFECA-IO/TideBit-DeFi/assets/20677913/711d43cd-5638-4173-af34-6cfa15c276eb)
![image](https://github.com/CAFECA-IO/TideBit-DeFi/assets/20677913/3ec0245c-6023-456f-93f2-82fda9593bca)
![image](https://github.com/CAFECA-IO/TideBit-DeFi/assets/20677913/fd10263e-cf5d-4ae8-917e-730361660aa7)
