### ISSUE TITLE
[BUG] 關倉時的報價落差太大

### ISSUE THREAD

**Issue by Julian0701** [CAFECA-IO/TideBit-DeFi#722]
![image](https://github.com/CAFECA-IO/TideBit-DeFi/assets/20677913/5479ce80-c30f-42fe-a14e-9cb0fda363b8)

![image](https://github.com/CAFECA-IO/TideBit-DeFi/assets/20677913/821ba8b8-ef8b-4a42-ac17-d58e0f64c2f8)

**Comment by arealclimber** [comment]
taking 2 hr
