### ISSUE TITLE
[BUG] NavBar 裡面的 user pnl 與 history list 裡面的資料不一致

### ISSUE THREAD

**Issue by TzuHanLiang** [CAFECA-IO/TideBit-DeFi#723]
- [x] 檢查 userCtx 計算 pnl 總和的公式是否正確
- [x] 一開始登入的時候會拿不到 pnl 資料，需檢查原因

**Comment by Julian0701** [comment]
<img width="699" alt="image" src="https://github.com/CAFECA-IO/TideBit-DeFi/assets/114177573/6b8d2497-7b60-4719-bb41-44694244d03d">

要先拿到 CFD 資料才能算出 User Assets 的 PNL ，所以調整了順序

- take 5 hrs
