### ISSUE TITLE
手機分享需用 deep link

### ISSUE THREAD

**Issue by arealclimber** [CAFECA-IO/TideBit-DeFi#730]
- [ ] Facebook
- [x] Twitter
- [ ] Reddit

**Comment by arealclimber** [comment]
- Facebook
    - URL scheme to post to Facebook
        - https://stackoverflow.com/questions/5707722/what-are-all-the-custom-url-schemes-supported-by-the-facebook-iphone-app
        - https://www.genuitec.com/forums/topic/facebook-url-scheme-fb/
        - https://gist.github.com/nhnam/5f106eaebff6366c0e21578c40515094
        - https://www.tutorialspoint.com/what-are-all-the-custom-url-schemes-supported-by-the-facebook-iphone-app
        - https://community.glideapps.com/t/launch-facebook-app-instead-of-browser-from-url/41209/9
            - https://app.urlgeni.us/
        - https://solito.dev/recipes/deep-linking
        - https://stackoverflow.com/questions/27839868/facebook-share-deep-linking-javascript
    - Facebook SDK for JS
        - Example
            - https://developers.facebook.com/docs/sharing/reference/share-dialog
            - https://developers.facebook.com/docs/javascript/examples#dialogs
        - Test console
            - https://developers.facebook.com/tools/console/
        - JS fiddle example
            - https://jsfiddle.net/api/post/library/pure/

**Comment by Julian0701** [comment]
- take 3 hrs

- Facebook 、Reddit 之前的提供的 url 已失效，只能導向首頁

https://stackoverflow.com/questions/73941107/can-not-open-facebook-page-in-the-app-from-a-link-in-ios-browser

https://stackoverflow.com/questions/32410196/is-there-a-way-to-submit-a-text-post-on-reddit-via-a-url/32533431#32533431
