### ISSUE TITLE
各個新聞頁面

### ISSUE THREAD

**Issue by arealclimber** [CAFECA-IO/TideBit-DeFi#754]
- [x] 各個新聞頁面
    - [x] 排版
    - [x] 分享至社群媒體
    - [x] 推薦閱讀
    
Ref:
[Mockup](https://xd.adobe.com/view/920d36bd-2d1a-4edd-8a2a-824445f1d3b0-c75e/screen/d8cf92d2-5a6b-4dcb-8582-ca932466b9fd/)

**Comment by arealclimber** [comment]
taking 4 hrs

**Comment by Luphia** [comment]
- typography issue
- thumbnail issue

**Comment by arealclimber** [comment]
taking 1 hr

- 補充 [KM](https://github.com/CAFECA-IO/KnowledgeManagement/blob/master/TideBit-DeFi/generate_img_share_url.md#%E8%A6%81%E8%A8%AD%E5%AE%9A%E7%9A%84-html-tag)
- 調整排版
