### ISSUE TITLE
Trading Page - 下單區 行動版

### ISSUE THREAD

**Issue by arealclimber** [CAFECA-IO/TideBit-DeFi#77]
Ref:

- [TideBit DeFi 設計稿電腦版 Spec](https://xd.adobe.com/view/920d36bd-2d1a-4edd-8a2a-824445f1d3b0-c75e/screen/1efeff4c-2c35-4644-aa82-40fd9e9bf9fe/specs/)
- [TideBit DeFi 設計稿手機版 Spec](https://xd.adobe.com/view/b4bc1f81-78f4-4de9-979f-20cb0d457d70-e1ef/screen/52e1328b-a83e-4c59-a3be-f5ca82af482f)
- [TBDSD00001.md (interaction between frontend and backend)](https://github.com/CAFECA-IO/Documents/blob/main/TBD/TBDSD00001.md)
- [Component Diagram](https://github.com/CAFECA-IO/Documents/blob/main/TBD/TBDCP00001.md)
- [Class Diagram](https://github.com/CAFECA-IO/Documents/blob/main/TBD/TBDCD00001.md)
- [Use Cases Diagram](https://github.com/CAFECA-IO/Documents/blob/main/TBD/TBDUC00001.md)

**Comment by Julian0701** [comment]
- take 4 hrs
- remain 8 hrs
- 將 position_tab_mobile 的 sub menu 高度設為填滿螢幕，再設定 padding top

**Comment by arealclimber** [comment]
如果用 `RippleButton ` 可以產生點擊產生漣漪效果

**Comment by Julian0701** [comment]
- [x]  125-OpenSubTabMobile
- [x]  126-HistorySubTabMobile

- take 3 hrs

**Comment by Julian0701** [comment]
- take 5 hrs
- remain 5 hrs
- trade tab mobile
  - sub menu 展開時，按鈕放大
  - 整理 sub menu 排版
  - Short Section

**Comment by Julian0701** [comment]
- remain 3 hrs
- 檢查 margin setting 內的佈局
- <TradingInput /> 的參數改掉

**Comment by Julian0701** [comment]
- take 1 hr
- done
