### ISSUE TITLE
[BUG] 在列表看關倉是會賺錢，但是一點開看後就變成賠錢，但後面的列表還是顯示賺

### ISSUE THREAD

**Issue by TzuHanLiang** [CAFECA-IO/TideBit-DeFi#772]
<img width="1680" alt="Screenshot 2023-06-01 at 2 11 11 PM" src="https://github.com/CAFECA-IO/TideBit-DeFi/assets/17249354/2f708f4e-84ef-4e86-a6a3-42094db9adc8">

**Comment by TzuHanLiang** [comment]
``` 
const spread = this.STOP_FEE_BASE * Math.abs(fluctuating); // Info: 點差 (spread) 也是透過價格波動來計算 (same as stopfee) (20230426 - tzuhan)
```

**Comment by arealclimber** [comment]
合併至 [#792](https://github.com/CAFECA-IO/TideBit-DeFi/issues/792) 處理
