### ISSUE TITLE
[BUG] Nav PNL 與各交易對的 PNL 加總結果不一致

### ISSUE THREAD

**Issue by arealclimber** [CAFECA-IO/TideBit-DeFi#843]
# Environment Description

- Machine: Desktop
- OS version: Windows 10
- Browser version: Brave v1.51.118 Chromium v113.0.5672.126

# How to reproduce
- 在 BTC 交易對關倉， PNL 會大幅改變

# Current Result

[nav-pnl-not-sum-all-tickers-pnl.webm](https://github.com/CAFECA-IO/TideBit-DeFi/assets/20677913/dce4b7d4-ca33-4bb2-abe0-43c8d1bf9ffa)

![螢幕擷取畫面 (941)](https://github.com/CAFECA-IO/TideBit-DeFi/assets/20677913/48c4bce6-0145-441d-be02-4f6eaf14febe)

![螢幕擷取畫面 (943)](https://github.com/CAFECA-IO/TideBit-DeFi/assets/20677913/d4d663c1-b655-43b1-a22f-e5eea9880d7a)

<google-sheets-html-origin>
ETH | BTC
-- | --
3.75 | 34.89
  |  
11.6 | 14.23
-2.18 | 16.13
-1.34 | -4.21
-2.2 | 8.74
-0.19 |  
-0.11 |  
-1.33 |  
-0.27 |  
-0.99 |  
-0.34 |  
1.1 |  

# Expect Result
- NavBar 的 PNL 統計所有交易成果的 PNL

**Comment by TzuHanLiang** [comment]
- take 1hrs
