### ISSUE TITLE
[BUG] 切換交易對後的關倉，要拿該交易對的報價單

### ISSUE THREAD

**Issue by arealclimber** [CAFECA-IO/TideBit-DeFi#847]
- 前端: 
    - [x] close/open 時檢查拿到的報價單
    -  `quotation.ticker === 'ETH-USDT'`
- 後端: 
    - [x] closeOrder 時要檢查 quatation 的 ticker 及 targetAsset 是否與要關的 order 一致

**Comment by TzuHanLiang** [comment]
- take 0.5hrs

**Comment by arealclimber** [comment]
taking 1 hr

**Comment by TzuHanLiang** [comment]
https://github.com/CAFECA-IO/TideBit-DeFi/assets/17249354/66c93b6a-431c-4e37-8f9b-0eda396a272f

找到再現的方法

**Comment by arealclimber** [comment]
- [ ] 顯示關倉確認視窗前應該檢查是否拿到該交易對的報價單
