### ISSUE TITLE
[BUG] Open tab bugs after opening position

### ISSUE THREAD

**Issue by arealclimber** [CAFECA-IO/TideBit-DeFi#862]
# Environment Description

- Machine: Desktop
- OS version: Windows 10
- Browser version: Brave v1.51.118 Chromium v113.0.5672.126

# How to reproduce
- 登入後到 ETH 開 up 跟 down 各一張，再到 Open sub tab ，會發現之前的倉位都消失了，只剩下剛剛開的兩張；重新整理之後才會正常顯示
- 市價 1730.02，但1728.32的空單、1733.6的多單竟然是賺錢的

# Current Result
![image](https://github.com/CAFECA-IO/TideBit-DeFi/assets/20677913/8780952a-2f88-4fd6-84ea-2fe3604a09af)
![image](https://github.com/CAFECA-IO/TideBit-DeFi/assets/20677913/af97012c-4e26-41f0-8226-88c6885f4e56)

# Expect Result
- 開完倉，之前的倉位不應該消失
- 多單空單的 PNL 應顯示正確數字

**Comment by TzuHanLiang** [comment]
- take 3hrs
