### ISSUE TITLE
[BUG] Closing position has incorrect PNL

### ISSUE THREAD

**Issue by arealclimber** [CAFECA-IO/TideBit-DeFi#864]
# Environment Description

- Machine: Desktop
- OS version: Windows 10
- Browser version: Brave v1.51.118 Chromium v113.0.5672.126

# How to reproduce
- 多單跟空單的 PNL 有誤

# Current Result
![image](https://github.com/CAFECA-IO/TideBit-DeFi/assets/20677913/71f153a4-89b5-4dd4-a3d1-a1559b1d4d53)

![image](https://github.com/CAFECA-IO/TideBit-DeFi/assets/20677913/21187df2-f209-486c-a51c-08700bf01855)

# Expect Result
- Close position 的 PNL 應顯示正確數字

**Comment by TzuHanLiang** [comment]
- take 2hrs
