### ISSUE TITLE
[BUG] Balance on NavBar doesn't change immediately after closing the position

### ISSUE THREAD

**Issue by arealclimber** [CAFECA-IO/TideBit-DeFi#885]
# Environment Description

- Machine: Desktop
- OS version: Windows 10
- Browser version: Brave v1.51.118 Chromium v113.0.5672.126

# How to reproduce
- 關倉

# Current Result
[fixedPnl-after-closingPosition.webm](https://github.com/CAFECA-IO/TideBit-DeFi/assets/20677913/21293c51-4319-45a6-b809-9517280727f5)

# Expect Result
- 關倉後應更新 NavBar 的 Avbl. Margin PNL 金額

**Comment by TzuHanLiang** [comment]
- take 3hrs
- 兩個 PR 前後端都要合才會修好
  - [PR#38](https://github.com/CAFECA-IO/tbd-backend/pull/38)
  - PR#908

**Comment by arealclimber** [comment]
- 開倉或關倉後，NavBar 的餘額沒有立即變化，影片為關倉示例

[avbl-pnl-no-change-after-closePosition.webm](https://github.com/CAFECA-IO/TideBit-DeFi/assets/20677913/47e908a9-22df-4178-afe2-4b3f4eb9b10a)

**Comment by arealclimber** [comment]
觀察至8/14，問題沒有重現
