### ISSUE TITLE
[BUG]  UserContext 的  getRanking 及 getPersonalRanking 已經被 MarketContext getLeaderboard 取代

### ISSUE THREAD

**Issue by TzuHanLiang** [CAFECA-IO/TideBit-DeFi#909]
- UserContext 的  getRanking 及 getPersonalRanking 已經被 MarketContext getLeaderboard 取代，所以前端是不需要呼叫的

<img width="1792" alt="Screenshot 2023-06-17 at 2 42 18 PM" src="https://github.com/CAFECA-IO/TideBit-DeFi/assets/17249354/90773046-6b7c-4ae2-b742-bc4d47b87a79">

**Comment by Julian0701** [comment]
- take 3 hrs
