### ISSUE TITLE
[BUG] getPersonalAchievement 裡面有提供 Badges 但畫面沒有顯示

### ISSUE THREAD

**Issue by TzuHanLiang** [CAFECA-IO/TideBit-DeFi#910]
<img width="1792" alt="Screenshot 2023-06-17 at 2 43 58 PM" src="https://github.com/CAFECA-IO/TideBit-DeFi/assets/17249354/eb8a16cf-bfc1-445b-9acc-ddef89303501">

**Comment by Julian0701** [comment]
- take 4 hrs
