### ISSUE TITLE
[BUG] 重新整理後交易會被登出

### ISSUE THREAD

**Issue by TzuHanLiang** [CAFECA-IO/TideBit-DeFi#947]
- duplicate DeWT

**Comment by arealclimber** [comment]
[clear-dewt-didnt-work.webm](https://github.com/CAFECA-IO/TideBit-DeFi/assets/20677913/edc0c721-9979-4bff-8eef-482149499cef)

**Comment by arealclimber** [comment]
重新整理後關倉，還沒送 API request 就失敗了；錯誤代碼40430002是 service term disable

![image](https://github.com/CAFECA-IO/TideBit-DeFi/assets/20677913/501d5a7a-8908-44b6-82ab-e24d66b59d5b)

![image](https://github.com/CAFECA-IO/TideBit-DeFi/assets/20677913/86580133-5f89-4fec-bd5f-b819604b4269)


[fail close after refreshing the tab.webm](https://github.com/CAFECA-IO/TideBit-DeFi/assets/20677913/29cdbd18-3c2c-4de2-b80e-25f9d00f231a)

**Comment by TzuHanLiang** [comment]
- take 6hrs
