### ISSUE TITLE
[BUG] live蠟燭圖會突然全部消失

### ISSUE THREAD

**Issue by TzuHanLiang** [CAFECA-IO/TideBit-DeFi#987]
可能是讀資料時，讀錯資料格式，才會一閃一閃的

![image](https://github.com/CAFECA-IO/TideBit-DeFi/assets/20677913/8e3ff4c4-e0e4-427a-a6ef-72d7317b00ac)

**Comment by arealclimber** [comment]
觀察至8/14，問題沒有重現
